name: Funder_API
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - selenium
  - pip
  - pip:
      - webdriver-manager
      - boto3



# to create the virtual envrinment 
#conda env create -f environment.yml

# To activate this environment, use
#
#     $ conda activate Funder_API
#
# To deactivate an active environment, use
#
#     $ conda deactivate

# to use airflow and use aws and databricks operators
# pip install "apache-airflow[amazon,databricks]==2.7.0" \
#   --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.7.0/constraints-3.11.txt"